FROM suse-base

ARG INTEGRATION
ARG TAG
ARG PKGDIR
ARG UPGRADE=false

ADD ${PKGDIR} ./dist

RUN if [ "${UPGRADE}" = "true" ]; then zypper -n install ${INTEGRATION}; fi; \
    zypper -n install ./dist/${INTEGRATION}-${TAG}-1.x86_64.rpm
