FROM centos-base

ARG INTEGRATION
ARG TAG
ARG PKGDIR
ARG UPGRADE=false

ADD ${PKGDIR} ./dist

RUN if [ "${UPGRADE}" = "true" ]; then yum -y install ${INTEGRATION}; fi; \
    yum -y install ./dist/${INTEGRATION}-${TAG}-1.x86_64.rpm
