FROM pgallina/suse-test as suse-test
ARG INTEGRATION=nri-apache
ARG TAG=0.0.1
RUN echo "suse-test-test for ${INTEGRATION} ${TAG}"
RUN wget https://github.com/newrelic/${INTEGRATION}/releases/download/v${TAG}/${INTEGRATION}-${TAG}-1.x86_64.rpm
RUN zypper -n install ./${INTEGRATION}-${TAG}-1.x86_64.rpm
RUN /var/db/newrelic-infra/newrelic-integrations/bin/${INTEGRATION} -show_version | grep ${TAG}


FROM pgallina/debian-test as debian-test-update
ARG INTEGRATION=nri-apache
ARG TAG=0.0.1
RUN echo "debian-test-update for ${INTEGRATION} ${TAG}"
RUN wget https://github.com/newrelic/${INTEGRATION}/releases/download/v${TAG}/${INTEGRATION}_${TAG}-1_amd64.deb
RUN apt install -y ${INTEGRATION}
RUN apt install -y --allow-downgrades ./${INTEGRATION}_${TAG}-1_amd64.deb
RUN /var/db/newrelic-infra/newrelic-integrations/bin/${INTEGRATION} -show_version | grep ${TAG}
