FROM pgallina/suse-test as suse-test
ARG INTEGRATION=nri-apache
ARG TAG=0.0.1
ARG TEST_EXISTENCE=""
RUN echo "suse-test-test for ${INTEGRATION} ${TAG}"
RUN zypper -n install ./dist/${INTEGRATION}-${TAG}-1.x86_64.rpm
RUN ls $TEST_EXISTENCE
RUN /var/db/newrelic-infra/newrelic-integrations/bin/${INTEGRATION} -show_version | grep ${TAG}


FROM pgallina/debian-test as debian-test-update
ARG INTEGRATION=nri-apache
ARG TAG=0.0.1
ARG TEST_EXISTENCE=""
RUN echo "debian-test-update for ${INTEGRATION} ${TAG}"
RUN apt install -y ${INTEGRATION}
RUN apt install -y --allow-downgrades ./dist/${INTEGRATION}_${TAG}-1_amd64.deb
RUN ls $TEST_EXISTENCE
RUN /var/db/newrelic-infra/newrelic-integrations/bin/${INTEGRATION} -show_version | grep ${TAG}
