FROM debian-test

ARG INTEGRATION=nri-apache
ARG TAG=0.0.1
ARG UPGRADE=false

ADD ./dist ./dist

RUN if [ "${UPGRADE}" = "true" ]; then apt install -y ${INTEGRATION}; fi; \
    apt install -y ./dist/${INTEGRATION}_${TAG}-1_amd64.deb
