FROM ubuntu:focal as debian-test

# Installing needed tools
RUN apt update && \
    apt -y install wget gnupg

ARG AGENT_PACKAGE=newrelic-infra_upstart_1.14.2_upstart_amd64.deb
# Installing Agent
RUN wget https://download.newrelic.com/infrastructure_agent/linux/apt/pool/main/n/newrelic-infra/${AGENT_PACKAGE} && \
    apt install ./${AGENT_PACKAGE}

# Adding Newrelic repository
RUN wget https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg -O - | apt-key add - && \
    echo "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt focal main" > /etc/apt/sources.list.d/newrelic-infra.list && \
    apt update
