name: 'Test packages installation'
description: 'This action test packages installation in Suse, Rocky Linux and Ubuntu'
inputs:
  tag:
    description: 'Tag of the integration to test'
    required: true
    default: '0.0.0'
  integration:
    description: 'Name of the integration to test'
    required: true
    default: 'nri-test'
  packageLocation:
    description: 'Location of the package to install. Valid options are "local" (dist folder) and "repo" (pulled from it)'
    required: false
    default: 'local'
  stagingRepo:
    description: 'Set to "true" to use the staging rather than the prod repo, for both upgrade test and install test.'
    required: false
    default: 'false'
  upgrade:
    description: 'Whether to test upgrade path as well'
    required: false
    default: "true"
  postInstall:
    description: 'Script to run after installation is completed. Default will test for existence of the integration binary and -show_version output'
    required: false
    default: ""
  postInstallExtra:
    description: 'Extra check lines to append to the default postInstall script.'
    required: false
    default: ""
  distros:
    description: 'Space-separated list of distros to run the test on. Supported values are "ubuntu", "suse" and "rockylinux"'
    required: false
    default: ""
  pkgDir:
    description: 'Folder containing installer packages'
    required: false
    default: ""

runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/action.sh
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        INTEGRATION: ${{ inputs.integration }}
        PACKAGE_LOCATION: ${{ inputs.packageLocation }}
        STAGING_REPO: ${{ inputs.stagingRepo }}
        UPGRADE: ${{ inputs.upgrade }}
        POST_INSTALL: ${{ inputs.postInstall }}
        POST_INSTALL_EXTRA: ${{ inputs.postInstallExtra }}
        DISTROS: ${{ inputs.distros }}
        PKGDIR: ${{ inputs.pkgDir }}
